# Generated by Django 2.1.5 on 2019-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.AddField(
            model_name='information',
            name='sex',
            field=models.CharField(default='', max_length=5),
        ),
    ]
